services:
    fervo_enum.form_guesser:
        class: Fervo\EnumBundle\Form\EnumTypeGuesser
        public: true
        arguments:
            - "@doctrine"
            - "%fervo_enum.form_type_classes%"
        tags:
            - { name: form.type_guesser }

    fervo_enum.twig_extension:
        class: Fervo\EnumBundle\Twig\EnumExtension
        public: false
        arguments:
            - "@translator"
            - "%fervo_enum.enum_map%"
        tags:
            - { name: twig.extension }

    fervo_enum.jms_serializer.enum_handler:
        class: Fervo\EnumBundle\Serializer\JMS\EnumHandler
        public: true
        arguments:
            - '@translator'

    fervo_enum.symfony_serializer.enum_normalizer:
        class: Fervo\EnumBundle\Serializer\Symfony\EnumNormalizer
        public: false
        arguments:
            - '@translator'
        tags:
            - {name: serializer.normalizer, priority: 8}

    fervo_enum.param_converter:
        class: Fervo\EnumBundle\ParamConverter\EnumParamConverter
        tags:
            - { name: request.param_converter, converter: enum }